dieu = ['Quand je demande une question, tu sais à qui je demande ? Moi.',
        "La drogue, faut pas toucher, c'est sérieux... Moi j'ai touché, j'ai perdu le touch, je n'avais plus le feeling de la vie... Ma brain était à l'envers dans ma tête. La drogue, c'est comme quand tu closes your eyes et que tu traverses la rue...",
        "Ah non mais attention quand je parle de l'enveloppe tu vois, je parle pas l'enveloppe que tu envoies par la poste. Je parle de l'enveloppe que tu vois. Celle qui enveloppe tout. Les paquets de biscuits, les sachets de cocaïne, ton esprit, etc ... Non, l'enveloppe c'est vraiment global.. Mais uniquement liée au spirit généralement. Oui alors un biscuit tu me diras ça n'a pas de spirit, c'est juste un biscuit. Mais avant, c'était du lait, des oeufs. Et dans les oeufs, il y a la vie potentielle... Le potential life dans une coquille, une enveloppe ... qui elle même était contenu dans la poule . eh oui... Non vraiment tout ça c'est une question d'awareness ... et puis même si le biscuit est physiquement différent d'une bouteille de lait, d'une poule ... il subsiste le spirit de la bouteille et de la poule dans le biscuit ... et ça toi tu le ressens quand tu le manges. Et que parfois c'est bon parfois c'est pas bon. C'est pour ça que j'ai fais des films avec des réplicants. Pour montrer que parfois tout se ressemble physiquement (l'enveloppe), mais que le spirit est totally différent ... il y a le mec gentil, le mec pourri... et tout ça c'est moi. Et oui ... Et en plus, c'est moi ! Car moi je suis acteur ! Alors quand je joue un rôle, il y a le personnage, son répliquant ..et moi. Donc, on est deux plus un, et c'est moi. Donc un. Donc quand il y a un gentil, un méchant, il y a aussi moi avec mon caractère ... quand tu fais le calcul tu obtiens ce que je suis. Alors après il faut intégrer tout ça dans LES environnements et alors ça se complexifie. Car quand je suis dans ma Mercedes je suis un violent roader ! Ou un dead drunk driver ! Mais sur le tournage je suis parfois répliquant. Alors quand je remonte dans ma Mercedes je ne suis plus un répliquant. Il ne faut pas se tromper .... Tu comprends ?",
        "Le Cycle... le cycle du cosmos dans la vie... c'est une grande roue. Qui est faite de... choses, de moments, de 'feelings'... et la vérité, c'est qu'il n'y a pas de vérité; la vérité, c'est qu'il faut trouver sa propre vérité. Ma vérité à moi? Comment veux-tu que je te parle de cette manière? Tu m'aurais parlé il y a cinq ans, ou bien il y a trois ans, ou il y a six mois! Ou hier... ou demain... Tu m'aurais parlé de cette manière, j'aurais pas pu te répondre de cette façon. Et grâce à ma propre vérité (dont je n'ai pas encore la réponse de la vérité), je peux te parler d'une manière plus sophistiquée. Il y a un an, je t'aurais parlé de mes muscles. De combien je mange le matin, combien je suis beau et combien je suis fort, je suis le meilleur... Mais en vérité, il n'y a pas de meilleur! En vérité, il y a chacun soi-même!",
        "Je crois en Dieu....... un plus un égale un. Y'a Jean-Claude, y'a Dieu, dans le même corps. Si on peut s'unifier, on devient ce qu'on appelle les miracles, et chaque personne a le seigneur en soi. We're all one. Je crois VRAIMENT en Seigneur.",
        "Il faut que tu crois encore plus ce que tu crois, et quand tu commences à croire ce que tu crois, y a personne au monde qui peut te bouger ! - (s'adressant au public de Loft Story, excédé) Oh non arrêtez les clapements, merde à la fin, arrêtez ces histoires ! On n'est pas du show-bizness, okay ?",
        "Entre penser et dire, il y a un monde de différences (et ils sont près!). Une personne s'appelle 'dieu' et l'autre s'appelle 'être humain'. Et on est tous les deux la même chose au même niveau... mais 'dieu' voudrait qu'on pense la vérité sur nous-même et pas ce qu'on dit... Tu comprends ce que je veux dire? It's a paradigme, un 'paradigme' comme on dit en français, je crois... et bien je n'ai jamais fait une interview comme ça! Je ne sais pas pourquoi.",
        "Il y a la douleur physique (primaire) et la douleur mentale (qu'on se rappelle, les souvenirs de la vie) et puis il y a le spirit qui lui n'a aucune douleur puisque... the final conclusion of spirit is perfection !",
        "Pour moi le rêve - et pour tout le monde, même si les gens ne le savent pas (et même s'ils ne le savent pas, ils le savent), le rêve, it's a feeling, c'est une sensation, une sensation réelle qui se produit si on veut.",
        "Quand tu montes dans un ascenseur... tu penses. A des tas de choses; à des créations, à des gens, à des souvenirs... Donc on est jamais seul spirituellement! Mais physiquement, 'dans l'enveloppe', si je suis seul... eh bien... je suis là. Et je reste là. Jusqu'à ce que les portes s'ouvrent... Et puis je commence à marcher. Je bouge mon enveloppe. Vers ma mission de tous les jours...",
        "La plus belle religion qu'on puisse avoir, c'est de rentrer en soi-même et de digérer l'essence de la vie, se digérer soi-même et produire à partir de ça sa propre religion: l'instinct. Et l'aboutissement de l'instinct, c'est l'amour! Il faut apprendre à aimer. S'aimer d'abord soi-même pour pouvoir aimer les autres.",
        "Ma devise, c'est toujours : se recréer. Il faut se recréer... pour recréer... a better you. Et ça, c'est très dur ! Et, et, et, et.... c'est très facile en même temps.",
        "Mon modèle, c'est moi-même! Je suis mon meilleur modèle parce que je connais mes erreurs, mes qualités, mes victoires et mes défaites. Si je passe mon temps à prendre un autre modèle comme modèle, comment veux-tu que ce modèle puisse modeler dans la bonne ligne ?",
        "Moi, Adam et Ève, j'y crois plus tu vois, parce que je suis pas un idiot : la pomme, ça peut pas être mauvais, c'est plein de pectine...",
        "L'être humain a tellement l'habitude de parler et de regarder, temps en temps les gens qui sont aveugles sont plus awares que les gens qui voillent, parce qu'ils sont obligés de sentir les sensations, les gens qu'ils aiment pas, qu'ils aiment bien, et les objets qui sont, et on est aware.",
        "L'eau c'est quelque chose de concret mais pas concret. Parce que l'eau... peut me nourrir, mais aussi l'eau... peut me porter. Parce que l'eau... a des lois magiques. L'eau peut tenir des cargos dans la mer, des milliers de tonnes d'acier... C'est quelque chose qui a beaucoup de dimensions l'eau.",
        "Je crois au moment. S'il n'y a pas le moment, à ce moment-là, il faut arriver à ce moment-là, au moment qu'on veut.",
        "La vie c'est quelque chose de très fort et de très beau.... La vie appartient a tous les vivants. It's both a dream and a feeling. C'est être ce que nous ne sommes pas sans le rester. La vie c'est mourir aussi.... Et mourir c'est vraiment strong... c'est rester en vie au delà de la mort... Tous ceux qui sont morts n'ignorent pas de le savoir",
        "Les plantes par exemple, qui n'ont pas de mains, et pas d'oreilles,elles sentent les choses, les vibrations , elles sont plus aware que les autres species.",
        "arce qu'on a créé une réalité et dans notre réalité, on a inventé le temps: les 24 heures, les 365 jours par an. Ce qui est bien! Comme ça on sait que quand je traverse le living-room et que je marche de ma cheminée à ma fenêtre, ça prend 10 secondes mais pour l'oiseau, ça prend une seconde et pour l'oxygène 0 seconde!",
        "Entre toi et moi il y a un produit qui s'appelle un produit, et c'est un produit qui s'appelle l'oxygène, alors si tu fais ça (inspiration/expiration) comme ça, tu vis, mais si je tue l'oxygène comme sur la lune, tu meurs !!',
        'Une vache, ça te bouffe trois hectares, moi, avec trois hectares, je te fais deux mille kilos de riz... avec trois hectares, je te nourris Avignon, tu vois...",
        "Quand tu joues au Go.. faut être aware. Si t'es pas aware, tes pierres sont mortes, et toi avec.",
        "Marcel Proust, oui. Un peu comme moi. Longtemps il s'est couché aware.",
        "Le monde est composé de flèches et de molécules, et d'électricité,comme le Big-Bang tu vois, et tout ça ensemble, ça forme l'Univers.",
        "Une femme qui est enceinte, par exemple, elle est aware qu'elle attend un enfant.",
        "J'adore les cacahuetes. Tu bois une biere et tu en as marre du gout. Alors tu manges des cacahuetes. Les cacahuetes c'est doux et salé, fort et tendre,comme une femme. Manger des cacahuetes, it's a really strong feeling. Et apres tu as de nouveau envie de boire de la bière. Les cacahuetes c'est le mouvement perpétuel à la portée de l'homme.",
        "Une noisette, j'la casse entre mes fesses tu vois...",
        "Je suis fascine par l'air. Si on enlevait l'air du ciel, tous les oiseaux tomberaient par terre....Et les avions aussi.... En meme temps l'air tu peux pas le toucher...ca existe et ca existe pas...Ca nourrit l'homme sans qu'il ait faim...It's magic...L'air c'est beau en meme temps tu peux pas le voir, c'est doux et tu peux pas le toucher.....L'air c'est un peu comme mon cerveau...",
        "Y a des gens qui n'ont pas réussi parce qu'ils ne sont pas aware, ils ne sont pas 'au courant'. Ils ne sont pas à l'attention de savoir qu'ils existent. Les pauvres, ils savent pas. Il faut réveiller les gens. C'est-à-dire qu'y a des gens qui font leur travail, qui font leurs études, ils ont un diplôme, ils sont au contact tout ça. Tu as un rhume et tu fais toujours 'snif'. Faut que tu te mouches. Tu veux un mouchoir ? Alors y a des gens comme ça qui ne sont pas aware. Moi je suis aware tu vois, c'est un exemple, je suis aware.",
        "L'amour ! Pourriez-vous croire en l'amour... ce que vous croyez, vous étiez seul, l'amour, à y croire.",
        "Moi un Jean Valjean des temps modernes ? Euh, non, je n'ai jamais vu son film !",
        'Je suis AWARE!!!'
        ]

rand(1..8).times do
  File.delete('file.txt')
  File.write('file.txt', dieu.sample)
  exec('git add .')
  exec("git commit -m 'Today JCVD says...'")
  exec('git push origin master')
  sleep 300
  puts 'Send to Github'
end
